### PR TITLE
 Added compatibility with Symfony 4

### PR DESCRIPTION
**Pull request by novecode**

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Hi @novecode. Thanks for the contribution. Can you explain why you made this change?

**Comment by novecode** [comment]
Hi, I decided to do this PR because it was impossible to require composer-git-hooks in projects that were already using symfony/console v4.0.

**Comment by BrainMaestro** [comment]
Okay, fair enough. what of removing `7.0` from travis

**Comment by novecode** [comment]
symfony/console ^4.0 requires php ^7.1. It's why Travis build was failing:
```
    - Installation request for symfony/console v4.0.3 -> satisfiable by symfony/console[v4.0.3].
    - symfony/console v4.0.3 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
```

Perhaps best solution would be change .travis.yml to something like this:
```
language: php

matrix:
  include:
    - php: 7.0
      env: DEPS=dev SYMFONY_CONSOLE_VERSION='3.2.*'
    - php: 7.1
      env: DEVS=dev SYMFONY_CONSOLE_VERSION='4.0.*'

before_install:
  - composer require --no-update "symfony/console:${SYMFONY_CONSOLE_VERSION}";

install:
  - composer install
```

**Comment by BrainMaestro** [comment]
Okay, can you do that instead?

**Comment by novecode** [comment]
Yes, I have done it in this commit: [https://github.com/BrainMaestro/composer-git-hooks/pull/12/commits/32d67af44fbe6cb952dfc59b76dc8a25b032bca7]

Travis will check now PHP 5.6, 7.0 and 7.1 versions. I have added a composer.json validation too.

**Comment by BrainMaestro** [comment]
I don't think this project is compatible with PHP 5.6. It has PHP 7 only features. Also, the travis build isn't being triggered for some reason

**Comment by BrainMaestro** [comment]
@novecode thanks

**Pull request merged**
