### PR TITLE
Add Symfony 6 and Laravel 9 support

### PR DESCRIPTION
**Pull request by shaffe-fr**
Hi,
This PR adds support to Symfony 6 and Laravel 9.
Thanks

### CODE REVIEW

**Comment by Pixy** [comment]
Hi! 
Thanks a lot for this PR 😍 
Do you know if it's planned to merge it soon and create a new tag?

**Comment by shaffe-fr** [comment]
No, I have no idea. Any plan @BrainMaestro ?

**Comment by cbaigorri** [comment]
+1

**Comment by SOSTheBlack** [comment]
+1 urgent

**Comment by ZejdCicak** [comment]
+1 This would be much appreciated

**Comment by shaffe-fr** [comment]
If you want to use this PR now, you can update your composer.json file to add a custom repository:

```json
 "repositories": [
        {
            "type": "github",
            "url": "https://github.com/shaffe-fr/composer-git-hooks.git"
        }
]
```
and require the package using the `dev-patch-2` version:
```json
"require-dev": {
    "brainmaestro/composer-git-hooks": "dev-patch-2"
}
```

**Comment by BrainMaestro** [comment]
The other PR already added support. Thanks for contributing though

**Comment by BrainMaestro** [comment]
@shaffe-fr I think it's fine to drop support for versions that are EOL. Even if they still technically work

**Pull request closed without merging**
