### PR TITLE
Fix: Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### PR DESCRIPTION
**Pull request by ZejdCicak**

### CODE REVIEW

**Comment by ZejdCicak** [comment]
@BrainMaestro can we get a stable tag for 3.0 with these fixes please?

**Comment by ZejdCicak** [comment]
Great, thank you! I don't mind the alpha since we are using this repo on many projects right now, I just want it to be up to date tag-wise 👍

**Comment by ZejdCicak** [comment]
@BrainMaestro any update on the tag?

**Comment by Diegslapasteque** [comment]
Hello,
@ZejdCicak Thank for fixing this issue.
@BrainMaestro We need this fix too on our project because we now have php 8.2 installed too. Do you have any update on the tag?

**Pull request merged**
