### PR TITLE
Add php-cs-fixer support

### PR DESCRIPTION
**Pull request by joaorobertopb**
This PR Will:

- **Add PHP constraints:** _"^5.6 || >=7.0 <7.3"_
- **Add php-cs-fixer to require-dev**;
- **Add composer scripts**: _check-style_ & _fix-style_
- **Add CONTRIBUTING.md file**
- **Update README.md file**

### CODE REVIEW

**Comment by joaorobertopb** [comment]
We can check the code standard using git hook pre-commit like this:

**composer.json**
```json
"scripts": {
    "...": "...",
    "post-install-cmd": "php cghooks add --ignore-lock"
},
"extra": {
    "hooks": {
         "pre-commit": "composer fix-style",
         "post-commit": "echo committed!"
    }
}
```

We can also provide more details this process in the _Contributing.md_ file ...

What do you think?

P.S: (Sorry, English is not my native language :sweat_smile:. Learning every day... :muscle:!)

**Comment by BrainMaestro** [comment]
This is amazing! 🎉 💯 I really like the `Contributing.md`. Good job 👍 
Could you add the `check-style` check to `.travis.yml`? So that it fails if the style is incorrect.

**Comment by joaorobertopb** [comment]
Done!

- Check code standards with php-cs-fixer
- Add composer cache directory ( accelerate the build process... )
- Add 'travis_retry' ( prevents Travis stay stuck...)

**Comment by BrainMaestro** [comment]
Ok one last thing. There's this message in travis 

> You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
> If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!

Can you check it out? It's nothing major, and I'll merge if you're not able to.

**Comment by joaorobertopb** [comment]
Humm... Of course! I'll check :smiley:

**Comment by joaorobertopb** [comment]
See: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1bf490754d9f1168e501c4e4eb8491a73c231f08/.travis.yml#L20

I'll add this ...

**Pull request merged**
