### PR TITLE
Allow symfony/console in version 7.0

### PR DESCRIPTION
**Pull request by jschaedl**

### CODE REVIEW

**Comment by glo71317** [comment]
@jschaedl Any idea when we can expect as stable version

**Comment by jschaedl** [comment]
Hi @glo71317 No idea. I am not the maintainer of that library. But I forked it. Feel free to use this version: https://packagist.org/packages/jschaedl/composer-git-hooks

**Comment by Tofandel** [comment]
Slightly improved the PR https://github.com/BrainMaestro/composer-git-hooks/pull/146

Seeing the graph activity of @BrainMaestro, I don't think anytime soon. Is he even still alive?

**Comment by BrainMaestro** [comment]
I merged the improved PR, so I'm closing this

**Pull request closed without merging**
