### PR TITLE
Add changes to Dockerfile

### PR DESCRIPTION
**Pull request by Smolevich**
Change instructions in Dockerfile

### CODE REVIEW

**Comment by BrainMaestro** [comment]
Hi @Smolevich. Thanks for contributing. Can you explain to me why you want to make this change?

**Comment by Smolevich** [comment]
On my opinion replacing `/app` on `.` seems like right way in Dockerfile

**Comment by BrainMaestro** [comment]
Hmm, I have not heard that before. Isn't `/app` clearer? Can you show me an example?

**Comment by Smolevich** [comment]
> Hmm, I have not heard that before. Isn't `/app` clearer? Can you show me an example?

```dockerfile
WORKDIR /app/path/to/longpath
COPY . /app/path/to/longpath
```
So `WORKDIR` automatically changed current dir then this record seems short
```dockerfile

WORKDIR /app/path/to/longpath
COPY . .
```

**Comment by BrainMaestro** [comment]
Okay, cool. You're right. Thanks

**Pull request merged**
