### PR TITLE
Update code for the git file issue

### PR DESCRIPTION
**Pull request by aman00323**
I have added, ability to find git directory, this code will try to find out **.git** directory from the root of the project as well as the parent directory of the project.

Most of have **git** initialize in their parent directory and composer in root directory so package will create **git** inside the folder where composer is placed.

This PR issue is mentioned here https://github.com/BrainMaestro/composer-git-hooks/issues/54

### CODE REVIEW

**Comment by glensc** [comment]
this approach is wrong, just invoke: `git rev-parse --absolute-git-dir` instead implementing git implementation details here.

**Comment by aman00323** [comment]
@glensc Would you help me out, when i tried to update code as you suggested it gives error in test case.

**Comment by aman00323** [comment]
@BrainMaestro Can you please dig in this, and let me know if it is going to help us out. Since i have tried @glensc Solution but it need more brief and changes in code.

The motive behind this PR is that previous code is taking COMPOSER path as git, So some of them don't have git in the same directory

**Comment by glensc** [comment]
@aman00323 I'm not palmist nor I have access to your computer. show the code, show the errors.

**Comment by aman00323** [comment]
@glensc you can see error log here. https://travis-ci.org/BrainMaestro/composer-git-hooks/jobs/537648797

**Comment by glensc** [comment]
I'm not going to find where is your code. link to it.

did you verify `git rev-parse --absolute-git-dir` that gives you proper value? also the git command needs to be run inside git directory or worktree, is your working directory accurate?

here's my output from random git project checkout:
```
➔ git rev-parse --absolute-git-dir
/Users/glen/scm/tmp/zf1/.git
```

considering your travis ci prints some git paths, are you using proper function to execute external command? verify that the command gives you the proper result. and also handle errors for invalid command execution.

**Comment by aman00323** [comment]
Here is the code that i have implemented, I have use php function to run the git command and get the working git directory so, package wouldn't take COMPOSER_HOME as root of the git, but it will take where git is originate.

https://github.com/BrainMaestro/composer-git-hooks/compare/8a22de1c51916125bed36666349109b2ea0fcaae..04f2a0b853870f501c2165b65619457bb44871ad#diff-3eec873d89d96a41d5ebb0ccf119a9ccR69

https://github.com/BrainMaestro/composer-git-hooks/compare/8a22de1c51916125bed36666349109b2ea0fcaae..04f2a0b853870f501c2165b65619457bb44871ad#diff-63bf48e7cc37afd5fb7c95230f7c554bR30

**Comment by glensc** [comment]
[system()](https://php.net/system) is wrong method to use. it outputs the command result:

```
➔ php -r '$gitPath = system("git rev-parse --absolute-git-dir");'
/Users/glen/scm/tmp/zf1/.git
```

but as it also returns the value, it's not the cause of your tests failing:
```
➔ php -r '$gitPath = system("git rev-parse --absolute-git-dir");var_dump($gitPath);'
/Users/glen/scm/tmp/zf1/.git
Command line code:1:
string(28) "/Users/glen/scm/tmp/zf1/.git"
```

**Comment by BrainMaestro** [comment]
Hi @aman00323 thanks for tackling the issue. I think @glensc's suggestion is pretty good. Do you need some assistance with handling it.

I think the first step should be to set up test scenarios. One which uses `git worktree` and another that uses a submodule, then go from there. Thanks for contributing!

**Comment by aman00323** [comment]
I have tried @glensc solution but here i am facing issue can you please help me out @glensc  and @BrainMaestro 

Here is the code that is have implemented 

https://github.com/BrainMaestro/composer-git-hooks/pull/79/files#diff-3eec873d89d96a41d5ebb0ccf119a9ccR69

https://github.com/BrainMaestro/composer-git-hooks/pull/79/files#diff-63bf48e7cc37afd5fb7c95230f7c554bR29

Here is the error that i am facing

https://travis-ci.org/BrainMaestro/composer-git-hooks/jobs/540732054

**Comment by BrainMaestro** [comment]
@aman00323 I will take a look later today

**Comment by Broutard** [comment]
My hooks are installed in a `--absolute-git-dir` directory ;)

```git --version
git version 2.11.0```

``` git rev-parse --absolute-git-dir
--absolute-git-dir```

**Pull request closed without merging**
