### PR TITLE
add support for custom shebang in git hooks

### PR DESCRIPTION
**Pull request by jdupak**
explained in code comments

### CODE REVIEW

**Review by BrainMaestro — APPROVED** [review]
Thanks! That makes sense

**Comment by jdupak** [comment]
Thanks for the approval, but you have to merge it as well. 
`Only those with write access to this repository can merge pull requests. `

**Comment by jdupak** [comment]
@BrainMaestro reminder, will you merge this?
`Only those with write access to this repository can merge pull requests. `

**Comment by jdupak** [comment]
@BrainMaestro ping

**Pull request merged**
